### ISSUE TITLE
different read/write mbps

### ISSUE THREAD

**Issue by yogeshVU** [cunnie/gobonniego#4]
Scenario:
on baremetal:
16 cores
16 threads running
rw ~ 40~mbps

On Docker container on the same baremetal server:
restricted to 2 cores:
2 threads running
rw ~150 mbps

Why such different output behavior?

![image](https://user-images.githubusercontent.com/8491735/38755083-09371f34-3f2a-11e8-83a6-f63c5a9b4af5.png)

**Comment by yogeshVU** [comment]
Also similar behaviour when increasing the core count of the docker to 16 cores

**Comment by cunnie** [comment]
That is very interesting behavior — completely unexpected.

My first question is this: what's the underlying OS (the baremetal OS)? If it's Unix (macOS, Linux, *BSD), the output of `uname -a` would be helpful.

Also, since I see 16 cores I assume some type of Intel Xeon, or perhaps Ryzen? If Linux, `cat /proc/cpuinfo`, but you only need to attach the output of the first core. I'm trying to determine exactly what type of chip you're running.

And congratulations — you're the first person other than me using the code.

**Comment by yogeshVU** [comment]
It's a Xeon processor with 16 cores. Will have the output to the command soon. It's running Ubuntu 16.04.

**Comment by cunnie** [comment]
Thanks, this looks like https://ark.intel.com/products/92986/Intel-Xeon-Processor-E5-2620-v4-20M-Cache-2_10-GHz

I'm going to run similar tests on a similar vintage Xeon D I have to see if I can replicate the behavior.

Thanks for the charts by the way — it demonstrates that the difference in throughput is consistent (i.e. there's not some other process running that's "stealing" the IO).

I must admit I'm a little baffled — the test doesn't use much CPU at all, it's all I/O — so even if there was another process for contending for CPU cycles, it shouldn't make much of a difference. Also the synchronization shouldn't be a big deal, either — it only synchronizes after writing 64 kiB. so even if there was a little lag it should be fine, but maybe I'll focus on the synchronization. Stay tuned.

**Comment by cunnie** [comment]
@yogeshVU  How much RAM? I'm guessing >= 32 GiB: 150 MB/s * 450 s = 67,000 MB =~ 64GiB data set size == 32 GiB RAM

**Comment by yogeshVU** [comment]
with respect to the CPU graph, the graph is only for the docker percentage. So initial half is when the docker is not running and the second half when the tests are actually carried out inside the docker container.

**Comment by yogeshVU** [comment]
Its having 32Gb
```
MemTotal:       32717372 kB
MemFree:        28445732 kB
MemAvailable:   31698292 kB
```

**Comment by yogeshVU** [comment]
More server info:
```
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                16
On-line CPU(s) list:   0-15
Thread(s) per core:    1
Core(s) per socket:    8
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 79
Model name:            Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz
Stepping:              1
CPU MHz:               1200.091
CPU max MHz:           3000.0000
CPU min MHz:           1200.0000
BogoMIPS:              4195.34
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              20480K
NUMA node0 CPU(s):     0,2,4,6,8,10,12,14
NUMA node1 CPU(s):     1,3,5,7,9,11,13,15

```

**Comment by cunnie** [comment]
I've been having difficulty recreating the slowdown you're seeing — although I see a drop-off in write performance when I use the full 16-threads, it's modest (1607 MB/s → 1282 MB/s), and I suspect it has more to do with the disk not being "warmed-up" (a follow-on run with 16 threads has an entirely reasonable 1563 MB/s).

Which leads me to ask the following: **What is the type of disk you're testing**? If you have a make and model, that's great, but if you only know, "it's a magnetic disk", that's good, too (I suspect it's magnetic because the throughput is too low for SSD).

I'm wondering if the mechanism I use — 16 threads spawns 16 different files being written simultaneously — is causing the disk head to thrash.

```
cunnie@artful:~/go/src/github.com/cunnie/gobonniego$ sudo go run gobonniego/gobonniego.go -v
2018/04/15 14:47:55 gobonniego starting. version: 1.0.9, runs: 1, seconds: 0, threads: 16, disk space to use (MiB): 7886
2018/04/15 14:47:55 Number of CPU cores: 16
2018/04/15 14:47:55 Total system RAM (MiB): 3943
2018/04/15 14:47:55 Bonnie working directory: /tmp/gobonniegoParent697368994
2018/04/15 14:48:01 Written (MiB): 7886
2018/04/15 14:48:01 Written (MB): 8269.070336
2018/04/15 14:48:01 Duration (seconds): 6.448985
Sequential Write MB/s: 1282.23
2018/04/15 14:48:07 Read (MiB): 7886
2018/04/15 14:48:07 Read (MB): 8269.070336
2018/04/15 14:48:07 Duration (seconds): 4.736989
Sequential Read MB/s: 1745.64
2018/04/15 14:48:23 operations 447000
2018/04/15 14:48:23 Duration (seconds): 15.005925
IOPS: 29788
cunnie@artful:~/go/src/github.com/cunnie/gobonniego$ sudo go run gobonniego/gobonniego.go -v -threads 8
2018/04/15 14:48:39 gobonniego starting. version: 1.0.9, runs: 1, seconds: 0, threads: 8, disk space to use (MiB): 7886
2018/04/15 14:48:39 Number of CPU cores: 16
2018/04/15 14:48:39 Total system RAM (MiB): 3943
2018/04/15 14:48:39 Bonnie working directory: /tmp/gobonniegoParent275247700
2018/04/15 14:48:44 Written (MiB): 7886
2018/04/15 14:48:44 Written (MB): 8269.070336
2018/04/15 14:48:44 Duration (seconds): 5.144056
Sequential Write MB/s: 1607.50
2018/04/15 14:48:50 Read (MiB): 7886
2018/04/15 14:48:50 Read (MB): 8269.070336
2018/04/15 14:48:50 Duration (seconds): 4.600640
Sequential Read MB/s: 1797.37
2018/04/15 14:49:05 operations 376895
2018/04/15 14:49:05 Duration (seconds): 15.004793
IOPS: 25118
cunnie@artful:~/go/src/github.com/cunnie/gobonniego$ sudo go run gobonniego/gobonniego.go -v -threads 4
2018/04/15 14:49:12 gobonniego starting. version: 1.0.9, runs: 1, seconds: 0, threads: 4, disk space to use (MiB): 7886
2018/04/15 14:49:12 Number of CPU cores: 16
2018/04/15 14:49:12 Total system RAM (MiB): 3943
2018/04/15 14:49:12 Bonnie working directory: /tmp/gobonniegoParent370520812
2018/04/15 14:49:17 Written (MiB): 7886
2018/04/15 14:49:17 Written (MB): 8269.070336
2018/04/15 14:49:17 Duration (seconds): 5.585691
Sequential Write MB/s: 1480.40
2018/04/15 14:49:24 Read (MiB): 7886
2018/04/15 14:49:24 Read (MB): 8269.070336
2018/04/15 14:49:24 Duration (seconds): 6.098622
Sequential Read MB/s: 1355.89
2018/04/15 14:49:40 operations 240497
2018/04/15 14:49:40 Duration (seconds): 15.000620
IOPS: 16032
cunnie@artful:~/go/src/github.com/cunnie/gobonniego$ sudo go run gobonniego/gobonniego.go -v -threads 2
2018/04/15 14:49:47 gobonniego starting. version: 1.0.9, runs: 1, seconds: 0, threads: 2, disk space to use (MiB): 7886
2018/04/15 14:49:47 Number of CPU cores: 16
2018/04/15 14:49:47 Total system RAM (MiB): 3943
2018/04/15 14:49:47 Bonnie working directory: /tmp/gobonniegoParent561904331
2018/04/15 14:49:57 Written (MiB): 7886
2018/04/15 14:49:57 Written (MB): 8269.070336
2018/04/15 14:49:57 Duration (seconds): 9.062680
Sequential Write MB/s: 912.43
2018/04/15 14:50:06 Read (MiB): 7886
2018/04/15 14:50:06 Read (MB): 8269.070336
2018/04/15 14:50:06 Duration (seconds): 9.144387
Sequential Read MB/s: 904.28
2018/04/15 14:50:21 operations 136038
2018/04/15 14:50:21 Duration (seconds): 15.000632
IOPS: 9069
cunnie@artful:~/go/src/github.com/cunnie/gobonniego$
```

**Comment by yogeshVU** [comment]
Yes, you are correct. It does not have SSD drives.

Interesting results, wrt write throughput from the above experiments.
The IOPS shows linear scaling with the increasing thread count. But the write throughput is less for the 16 threads than that of the 8 threads.

Also, could you try running the same inside a docker container? and see if you are getting any changes to the write mbps. You could try with the minimal docker image based on alpine container to start, and repeat the above tests.
Thanks again.

**Comment by cunnie** [comment]
I'm closing because it's been years.

Final notes: I suspect the baremetal-16-threads slowdown has more to do with threads than with Docker (i.e. a two-thread baremetal would be as performant as Docker container with 2 threads), but this is speculation.
